Vagrant.configure("2") do |config|

  config.vm.box = "cheretbe/routeros"

  config.vm.define "routeros" do |routeros|
    routeros.vm.network "private_network", type: "dhcp", auto_config: false
    routeros.vm.provider "virtualbox" do |vb|
      vb.gui = false
      vb.cpus = 1
      vb.memory = "516"
      vb.name = "MikroTik"
    end
    routeros.vm.provision "routeros_command", name: "Logging IP address router", command: "/ip address print"
  end
  
end
